baseURL: https://rzyn2020.github.io/
title: Ekstasis's Blog
theme: [archie]
ignoreLogs: ['warning-goldmark-raw-html']

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: "onedark"
    tabWidth: 4
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - $ 
            - $
        enable: true
menu:
  main:
    - name: All Posts
      url: /posts/
      weight: 1
    - name: Categories
      url: /categories/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: Algorithm
      url: https://rzyn2020.github.io/algorithm/
      weight: 4
      

taxonomies:
  category: categories
  tag: tags

params:
  mode: "auto"
  math: true
  social: # optional
    - name: "Github"
      url: "https://github.com/RZYN2020"
    - name: "Email"
      url: "mailto:zhaoyzzz@outlook.com"    
    - name: "Resume"
      url: "https://rzyn2020.github.io/resume/resume.html"
    - name: "Neodb"
      url: "https://neodb.social/users/Ekstasis"
    - name: "Mal"
      url: "https://myanimelist.net/animelist/yuki960"

module:
  mounts:
  - source: content
    target: content
  - source: blogs/tech
    target: content/posts
  - source: blogs/human
    target: content/posts
  - source: blogs/life
    target: content/posts