baseURL: https://rzyn2020.github.io/
title: Ekstasis's Blog
theme: [LoveIt]
ignoreLogs: ['warning-goldmark-raw-html']

menu:
  main:
    - name: All Posts
      url: /posts/
      weight: 1
    - name: Categories
      url: /categories/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    # - name: About
    #   url: /about/
    #   weight: 4
    - name: Algo
      url: https://rzyn2020.github.io/algorithm/
      weight: 4
    - name: CV
      url: https://rzyn2020.github.io/resume/
      weight: 5
    - name: Journal
      url: https://rzyn2020.github.io/journal/
      weight: 6
      

module:
  mounts:
  - source: content
    target: content
  - source: blogs/tech
    target: content/posts
  - source: blogs/human
    target: content/posts
  - source: blogs/life
    target: content/posts


taxonomies:
  category: categories
  tag: tags

hasCJKLanguage: true

enableRobotsTXT: true
enableEmoji: true

pagination:
  disableAliases: false
  pagerSize: 10
  path: "page"

#   math: true

params:

  defaultTheme: "auto"
  title: "Ekstasis's Blog"
  description: "Ekstasis's Blog"
  images: 
    - "/img/yinyang.webp"
  author:
    name: "Ekstasis"
    email: "zhaoyzzz@outlook.com"

  # Header config
  # 页面头部导航栏配置
  header:
    # desktop header mode ["fixed", "normal", "auto"]
    # 桌面端导航栏模式 ["fixed", "normal", "auto"]
    desktopMode: "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    # 移动端导航栏模式 ["fixed", "normal", "auto"]
    mobileMode: "auto"
    # Header title config
    # 页面头部导航栏标题配置
    title:
      # URL of the LOGO
      # LOGO 的 URL
      logo: "/img/yinyang.webp"
      # title name
      # 标题名称
      name: "Ekstasis's Blog"
      # you can add extra information before the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
      # pre: "<i class='far fa-kiss-wink-heart fa-fw' aria-hidden='true'></i>"
      # you can add extra information after the name (HTML format is supported), such as icons
      # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
      post: ""
      # whether to use typeit animation for title name
      # 是否为标题显示打字机动画
      typeit: false

  # Footer config
  # 页面底部信息配置
  footer:
    enable: true
    # Custom content (HTML format is supported)
    # 自定义内容 (支持 HTML 格式)
    # custom: "
    # whether to show Hugo and theme info
    # 是否显示 Hugo 和主题信息
    hugo: false
    # whether to show copyright info
    # 是否显示版权信息
    # copyright: true
    # whether to show the author
    # 是否显示作者
    author: true
    # site creation time
    # 网站创立年份
    since: 2021
    # ICP info only in China (HTML format is supported)
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    # icp: ""
    # license info (HTML format is supported)
    # 许可协议信息 (支持 HTML 格式)
    # license: '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

  # Section (all posts) page config
  # Section (所有文章) 页面配置
  section:
    # special amount of posts in each section page
    # section 页面每页显示文章数量
    paginate: 20
    # date format (month and day)
    # 日期格式 (月和日)
    dateFormat: "01-02"
    # amount of RSS pages
    # RSS 文章数目
    rss: 10

  # List (category or tag) page config
  # List (目录或标签) 页面配置
  list:
    # special amount of posts in each list page
    # list 页面每页显示文章数量
    paginate: 20
    # date format (month and day)
    # 日期格式 (月和日)
    dateFormat: "01-02"
    # amount of RSS pages
    # RSS 文章数目
    rss: 10

  # App icon config
  # 应用图标配置
  app:
    # optional site title override for the app when added to an iOS home screen or Android launcher
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title: "Ekstasis"
    # whether to omit favicon resource links
    # 是否隐藏网站图标资源链接
    noFavicon: false
    # modern SVG favicon to use in place of older style .png and .ico files
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
    # svgFavicon: ""
    # Android browser theme color
    # Android 浏览器主题色
    themeColor: "#ffffff"
    # Safari mask icon color
    # Safari 图标颜色
    iconColor: "#5bbad5"
    # Windows v8-11 tile color
    # Windows v8-11 磁贴颜色
    tileColor: "#da532c"

  # Search config
  # 搜索配置
  search:
    enable: true
    # type of search engine ["lunr", "algolia"]
    # 搜索引擎的类型 ["lunr", "algolia"]
    type: "algolia"
    # max index length of the chunked content
    # 文章内容最长索引长度
    contentLength: 4000
    # placeholder of the search bar
    # 搜索框的占位提示语
    placeholder: ""
    # max number of results length
    # 最大结果数目
    maxResultLength: 10
    # snippet length of the result
    # 结果内容片段长度
    snippetLength: 30
    # HTML tag name of the highlight part in results
    # 搜索结果中高亮部分的 HTML 标签
    highlightTag: "em"
    # whether to use the absolute URL based on the baseURL in search index
    # 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL: false
    algolia:
      index: ""
      appID: ""
      searchKey: ""

  # Home page config
  # 主页信息设置
  home:
    # amount of RSS pages
    # RSS 文章数目
    rss: 10
    # Home page profile
    # 主页个人信息
    profile:
      enable: true
      # Gravatar Email for preferred avatar in home page
      # Gravatar 邮箱，用于优先在主页显示的头像
      gravatarEmail: "zhaoyzzz@outlook.com"
      # URL of avatar shown in home page
      # 主页显示头像的 URL
      # title shown in home page (HTML format is supported)
      # 主页显示的网站标题 (支持 HTML 格式)
      title: "Ekstasis's Blog"
      # subtitle shown in home page (HTML format is supported)
      # 主页显示的网站副标题 (允许 HTML 格式)
      subtitle: "Amor Fati"
      # whether to use typeit animation for subtitle
      # 是否为副标题显示打字机动画
      typeit: false
      # whether to show social links
      # 是否显示社交账号
      social: true
      # disclaimer (HTML format is supported)
      # 免责声明 (支持 HTML 格式)
      # disclaimer: ""
    # Home page posts
    # 主页文章列表
    posts:
      enable: true
      # special amount of posts in each home posts page
      # 主页每页显示文章数量
      paginate: 6

  # Page global config
  # 文章页面全局配置
  page:
    # whether to hide a page from home page
    # 是否在主页隐藏一篇文章
    hiddenFromHomePage: false
    # whether to hide a page from search results
    # 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch: false
    # whether to enable twemoji
    # 是否使用 twemoji
    twemoji: false
    # whether to enable lightgallery
    # 是否使用 lightgallery
    lightgallery: false
    # whether to enable the ruby extended syntax
    # 是否使用 ruby 扩展语法
    ruby: true
    # whether to enable the fraction extended syntax
    # 是否使用 fraction 扩展语法
    fraction: true
    # whether to enable the fontawesome extended syntax
    # 是否使用 fontawesome 扩展语法
    fontawesome: true
    # whether to show link to Raw Markdown content of the content
    # 是否显示原始 Markdown 文档内容的链接
    # linkToMarkdown: true
    # whether to show the full text content in RSS
    # 是否在 RSS 中显示全文内容
    rssFullText: false
    # Table of the contents config
    # 目录配置
    toc:
      # whether to enable the table of the contents
      # 是否使用目录
      enable: true
      # whether to keep the static table of the contents in front of the post
      # 是否保持使用文章前面的静态目录
      keepStatic: false
      # whether to make the table of the contents in the sidebar automatically collapsed
      # 是否使侧边目录自动折叠展开
      auto: true
    # Code config
    # 代码配置
    code:
      # whether to show the copy button of the code block
      # 是否显示代码块的复制按钮
      copy: true
      # the maximum number of lines of displayed code by default
      # 默认展开显示的代码行数
      maxShownLines: 50
      render:
        goat: true
        mermaid: true
    # KaTeX mathematical formulas config (KaTeX https://katex.org/)
    # KaTeX 数学公式配置 (KaTeX https://katex.org/)
    math:
      enable: true
      # default inline delimiter is $ ... $ and \( ... \)
      # 默认行内定界符是 $ ... $ 和 \( ... \)
      inlineLeftDelimiter: ""
      inlineRightDelimiter: ""
      # default block delimiter is $$ ... $$, \[ ... \], \begin{equation} ... \end{equation} and some other functions
      # 默认块定界符是 $$ ... $$, \[ ... \],  \begin{equation} ... \end{equation} 和一些其它的函数
      blockLeftDelimiter: ""
      blockRightDelimiter: ""
      # KaTeX extension copy_tex
      # KaTeX 插件 copy_tex
      copyTex: true
      # KaTeX extension mhchem
      # KaTeX 插件 mhchem
      mhchem: true
    # Social share links in post page
    # 文章页面的分享信息设置
    share:
      enable: true
      X: true
      Threads: true
      Facebook: true
      Linkedin: false
      Whatsapp: false
      Pinterest: false
      Tumblr: false
      HackerNews: true
      Reddit: false
      VK: false
      Buffer: false
      Xing: false
      Line: true
      Instapaper: false
      Pocket: false
      Flipboard: false
      Weibo: true
      Blogger: false
      Baidu: false
      Odnoklassniki: false
      Evernote: false
      Skype: false
      Trello: false
      Diaspora: true
      Mix: false
      Telegram: true
  
  social:
    GitHub: "RZYN2020"
    Email: "zhaoyzzz@outlook.com"


  # Compatibility config
  # 兼容性设置
  compatibility:
    # whether to use Polyfill.io to be compatible with older browsers
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill: false
    # whether to use object-fit-images to be compatible with older browsers
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit: false

# Markup related configuration in Hugo
# Hugo 解析文档的配置
markup:
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
  # Goldmark is from Hugo 0.60 the default library used for Markdown
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    renderer:
      # whether to use HTML tags directly in the document
      # 是否在文档中直接使用 HTML 标签
      unsafe: true
  # Table Of Contents settings
  # 目录设置
  tableOfContents:
    startLevel: 2
    endLevel: 6

# Sitemap config
# 网站地图配置
sitemap:
  changefreq: "weekly"
  filename: "sitemap.xml"
  priority: 0.5


# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
mediaTypes:
  "text/plain":
    suffixes:
      - "md"

# Options to make output .md files
# 用于输出 Markdown 格式文档的设置
outputFormats:
  MarkDown:
    mediaType: "text/plain"
    isPlainText: true
    isHTML: false

# Options to make hugo output files
# 用于 Hugo 输出文档的设置
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "MarkDown"
  section:
    - "HTML"
    - "RSS"
  taxonomy:
    - "HTML"
    - "RSS"